fix order

diff --git a/prtl b/prtl
--- a/prtl
+++ b/prtl
@@ -8,6 +8,40 @@
 # Config location
 config="/etc/prt.conf"
 
+## FUNCTIONS
+
+# This function gets some basic info
+info() {
+	order="$(grep "^order" "$config" | cut -d " " -f 2-)"
+	alias="$(grep "^alias" "$config" | cut -d " " -f 2-)"
+
+	ports="$(ports -l)"
+	installed="$(pkginfo -i | cut -d " " -f 1)"
+}
+
+location() {
+	location="$(ports -l | grep "/$@$")"
+
+	# Order
+	# TODO: Find a better way of doing this?
+	if [ "$(echo "$location" | wc -l)" -ge 2 ]; then
+		for line in $order; do
+			locationorder="$(echo "$location" | grep "^$line/")"
+			if [ -n "$locationorder" ]; then
+				location="$locationorder"
+				break
+			fi
+		done
+	fi
+
+	if [ -d "/usr/ports/$location" -a -n "$location" ]; then
+		echo "/usr/ports/$location"
+	else
+		echo "prtl: invalid port $1"
+		exit 1
+	fi
+}
+
 
 ## EXECUTE
 
@@ -19,7 +53,7 @@ fi
 for flag in "$@"; do
 	case "$flag" in
 		-h|--help)
-			echo "Usage: prtl [options] [query]"
+			echo "Usage: prtl [options] [port]"
 			echo ""
 			echo "options:"
 			echo "  -v,   --version         print version and exit"
@@ -27,32 +61,12 @@ for flag in "$@"; do
 			exit 0
 			;;
 		-v|--version)
-			echo "prtl (prt-utils-extra) 0.7.4"
+			echo "prtl (prt-utils-extra) 0.7.5"
 			exit 0
 			;;
 		*)
-			location="$(ports -l | grep "/$@$")"
-
-			# Order
-			# TODO: Find a better way of doing this?
-			if [ "$(echo "$location" | wc -l)" -ge 2 ]; then
-				for line in $order; do
-					echo a
-					locationorder="$(echo "$location" | grep "^$line/")"
-					if [ -n "$locationorder" ]; then
-						location="$locationorder"
-						echo "$location"
-						break
-					fi
-				done
-			fi
-
-			if [ -d "/usr/ports/$location" -a -n "$location" ]; then
-				echo "/usr/ports/$location"
-			else
-				echo "prtl: invalid port $1"
-				exit 1
-			fi
+			info
+			location $@
 			;;
 	esac
 done
